/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazsalario;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class calculosalario extends javax.swing.JFrame {

    /**
     * Creates new form calculosalario
     */
    public calculosalario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Renda = new javax.swing.JCheckBox();
        Fonavi = new javax.swing.JCheckBox();
        afp = new javax.swing.JCheckBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        Rendatexto = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        Fonavitexto = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        afptexto = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        Diurn = new javax.swing.JRadioButton();
        nocturn = new javax.swing.JRadioButton();
        acceptar = new javax.swing.JButton();
        netejar = new javax.swing.JButton();
        eixir = new javax.swing.JButton();
        soubasic = new javax.swing.JLabel();
        hex = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sounet = new javax.swing.JTextField();
        Treballador = new javax.swing.JTextField();
        soubasictexto = new javax.swing.JTextField();
        hextratexto = new javax.swing.JTextField();
        pagahores = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Treballador");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Descomptes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        Renda.setText("Renda");
        Renda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RendaActionPerformed(evt);
            }
        });

        Fonavi.setText("Fonavi");
        Fonavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FonaviActionPerformed(evt);
            }
        });

        afp.setText("AFP");
        afp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afpActionPerformed(evt);
            }
        });

        Rendatexto.setContentType(""); // NOI18N
        Rendatexto.setText("0");
        Rendatexto.setEnabled(false);
        jScrollPane5.setViewportView(Rendatexto);

        Fonavitexto.setText("0");
        Fonavitexto.setEnabled(false);
        jScrollPane6.setViewportView(Fonavitexto);

        jScrollPane7.setEnabled(false);

        afptexto.setText("0");
        afptexto.setEnabled(false);
        afptexto.setFocusCycleRoot(false);
        jScrollPane7.setViewportView(afptexto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Renda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fonavi)
                            .addComponent(afp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane6))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Renda)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Fonavi))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(afp)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Torn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(Diurn);
        Diurn.setSelected(true);
        Diurn.setText("Diurn");
        Diurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiurnActionPerformed(evt);
            }
        });

        buttonGroup1.add(nocturn);
        nocturn.setText("Nocturn");
        nocturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nocturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nocturn)
                    .addComponent(Diurn))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Diurn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nocturn)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        acceptar.setText("Acceptar");
        acceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptarActionPerformed(evt);
            }
        });

        netejar.setText("Netejar");
        netejar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netejarActionPerformed(evt);
            }
        });

        eixir.setText("Eixir");
        eixir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eixirActionPerformed(evt);
            }
        });

        soubasic.setText("Sou bàsic / €");

        hex.setText("Hores extra");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html>Pagament </br>\nhora extra</html>");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Sou net / €");

        sounet.setEnabled(false);
        sounet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sounetActionPerformed(evt);
            }
        });

        pagahores.setText("30");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soubasic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hex, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pagahores, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(Treballador)
                            .addComponent(soubasictexto)
                            .addComponent(hextratexto))
                        .addGap(160, 160, 160))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sounet, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netejar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eixir, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Treballador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soubasic)
                            .addComponent(soubasictexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hex, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hextratexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pagahores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(netejar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eixir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(sounet))
                .addGap(27, 27, 27))
        );

        jLabel4.getAccessibleContext().setAccessibleName("Pagament\nhora extra"); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afpActionPerformed
      if (afp.isSelected()){
          double sbt = Double.parseDouble(soubasictexto.getText());
          double a = sbt * 0.03;
          afptexto.setText(Double.toString(a));
      }
      else{
          afptexto.setText("0");
      }
    }//GEN-LAST:event_afpActionPerformed

    private void netejarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netejarActionPerformed
        Treballador.setText("");
        soubasictexto.setText("");
        hextratexto.setText("");
        pagahores.setText("");
        Rendatexto.setText("0");
        Fonavitexto.setText("0");
        afptexto.setText("0");
        sounet.setText("0");
        Renda.setSelected(false);
        Fonavi.setSelected(false);
        afp.setSelected(false);
        Diurn.setSelected(false);
        nocturn.setSelected(false);
    }//GEN-LAST:event_netejarActionPerformed

    private void DiurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiurnActionPerformed
        if (Diurn.isSelected()){
            pagahores.setText("30");
        }     
    }//GEN-LAST:event_DiurnActionPerformed

    private void nocturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nocturnActionPerformed
        if (nocturn.isSelected()){
            pagahores.setText("40");
       }
    }//GEN-LAST:event_nocturnActionPerformed

    private void RendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RendaActionPerformed
        double r;
        double sbt;
        if (Renda.isSelected()){
            sbt = Double.parseDouble(soubasictexto.getText());
            r = sbt * 0.1;
            Rendatexto.setText(Double.toString(r));
        }
        else{
            Rendatexto.setText("0");
        }
    }//GEN-LAST:event_RendaActionPerformed

    private void FonaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FonaviActionPerformed
        if (Fonavi.isSelected()){
            double sbt = Double.parseDouble(soubasictexto.getText());
            double f = sbt *7/100;
            Fonavitexto.setText(Double.toString(f));
        }
        else{
            Fonavitexto.setText("0");
        } 
            
    }//GEN-LAST:event_FonaviActionPerformed

    private void sounetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sounetActionPerformed
           
             
            
    }//GEN-LAST:event_sounetActionPerformed

    private void acceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptarActionPerformed
            double sbt = 0;
            if (soubasictexto.getText().equals("")){
                JOptionPane.showMessageDialog(null,"El camp Sou básic no pot estar vuit","ERROR", JOptionPane.WARNING_MESSAGE);
            }
            else{
            sbt = Double.parseDouble(soubasictexto.getText());
            }
            double he ;
             if (hextratexto.getText().equals("")){
                he = 0;
            }
             else{
                he= Double.parseDouble(hextratexto.getText());
             }
            double phe = Double.parseDouble(pagahores.getText());
            double r = Double.parseDouble(Rendatexto.getText());
            double f = Double.parseDouble(Fonavitexto.getText());
            double a = Double.parseDouble(afptexto.getText());
      
        
           
            double sueldoneto = sbt + he * phe - r - f - a;
            
            sounet.setText(Double.toString(sueldoneto));    }//GEN-LAST:event_acceptarActionPerformed

    private void eixirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eixirActionPerformed
            System.exit(0);
    }//GEN-LAST:event_eixirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculosalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculosalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculosalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculosalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculosalario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Diurn;
    private javax.swing.JCheckBox Fonavi;
    private javax.swing.JTextPane Fonavitexto;
    private javax.swing.JCheckBox Renda;
    private javax.swing.JTextPane Rendatexto;
    private javax.swing.JTextField Treballador;
    private javax.swing.JButton acceptar;
    private javax.swing.JCheckBox afp;
    private javax.swing.JTextPane afptexto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton eixir;
    private javax.swing.JLabel hex;
    private javax.swing.JTextField hextratexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton netejar;
    private javax.swing.JRadioButton nocturn;
    private javax.swing.JTextField pagahores;
    private javax.swing.JLabel soubasic;
    private javax.swing.JTextField soubasictexto;
    private javax.swing.JTextField sounet;
    // End of variables declaration//GEN-END:variables
}
